// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksApi.Models;

#nullable disable

namespace ParksApi.Migrations
{
    [DbContext(typeof(ParksApiContext))]
    [Migration("20230422235705_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksApi.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AreaInAcres")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .HasColumnType("longtext");

                    b.Property<string>("GoverningBody")
                        .HasColumnType("longtext");

                    b.Property<string>("LocationState")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext");

                    b.Property<string>("URL")
                        .HasColumnType("longtext");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            AreaInAcres = 922650,
                            Designation = "National Park",
                            GoverningBody = "NPS",
                            LocationState = "Washington",
                            ParkCode = "OLYM",
                            ParkName = "Olympic National Park",
                            URL = "https://www.nps.gov/olym/index.htm"
                        },
                        new
                        {
                            ParkId = 2,
                            AreaInAcres = 3373063,
                            Designation = "National Park",
                            GoverningBody = "NPS",
                            LocationState = "California",
                            ParkCode = "DEVA",
                            ParkName = "Death Valley National Park",
                            URL = "https://www.nps.gov/deva/index.htm"
                        },
                        new
                        {
                            ParkId = 3,
                            AreaInAcres = 1159801,
                            Designation = "National Forest",
                            GoverningBody = "USFS",
                            LocationState = "Arkansas",
                            ParkCode = "osfnf",
                            ParkName = "Ozark-St. Francis National Forest",
                            URL = "https://www.fs.usda.gov/osfnf"
                        },
                        new
                        {
                            ParkId = 4,
                            AreaInAcres = 759620,
                            Designation = "National Park",
                            GoverningBody = "NPS",
                            LocationState = "California",
                            ParkCode = "YOSE",
                            ParkName = "Yosemite National Park",
                            URL = "https://www.nps.gov/yose/index.htm"
                        },
                        new
                        {
                            ParkId = 5,
                            AreaInAcres = 1071466,
                            Designation = "National Forest",
                            GoverningBody = "USFS",
                            LocationState = "Oregon",
                            ParkCode = "mthood",
                            ParkName = "Mt. Hood National Forest",
                            URL = "https://www.fs.usda.gov/mthood"
                        },
                        new
                        {
                            ParkId = 6,
                            AreaInAcres = 0,
                            Designation = "National Monument",
                            GoverningBody = "NPS",
                            LocationState = "Wyoming",
                            ParkCode = "DETO",
                            ParkName = "Devil's Tower National Monument",
                            URL = "https://www.nps.gov/deto/index.htm"
                        },
                        new
                        {
                            ParkId = 7,
                            AreaInAcres = 9000,
                            Designation = "State Park",
                            GoverningBody = "OPRD",
                            LocationState = "Oregon",
                            ParkName = "Silver Falls State Parlk",
                            URL = "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=151"
                        },
                        new
                        {
                            ParkId = 8,
                            AreaInAcres = 183224,
                            Designation = "National Park",
                            GoverningBody = "NPS",
                            LocationState = "Oregon",
                            ParkCode = "CRLA",
                            ParkName = "Crater Lake National Park",
                            URL = "https://www.nps.gov/crla/index.htm"
                        },
                        new
                        {
                            ParkId = 9,
                            AreaInAcres = 8472506,
                            Designation = "National Park",
                            GoverningBody = "NPS",
                            LocationState = "Alaska",
                            ParkCode = "GAAR",
                            ParkName = "Gates Of The Arctic National Park",
                            URL = "https://www.nps.gov/gaar/index.htm"
                        },
                        new
                        {
                            ParkId = 10,
                            AreaInAcres = 8472506,
                            Designation = "National Park",
                            GoverningBody = "NPS",
                            LocationState = "Florida",
                            ParkCode = "EVER",
                            ParkName = "Everglades National Park",
                            URL = "https://www.nps.gov/gaar/index.htm"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
